id: A4DAAD040
title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:58:36.647372
  last_modified_at: 2022-03-01 01:58:36.647379
